### ISSUE TITLE
Develop Homework for Friday #1

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-au15#16]

**Comment by jayfo** [comment]
Homework for this Friday is now drafted.

Verify it looks good? @milnel2 @fiannaca 

https://courses.cs.washington.edu/courses/cse440/15au/assignments/assignment1/#project_brainstorm

**Comment by milnel2** [comment]
I think it looks good. Definitely useful to define domains.

**Comment by skawas** [comment]
It looks good. One thought to include to help them identify a domain is to mention possibilities or design opportunities where tracking / data gather might provide insights/ possible solutions.... also think of a profession where data tracking might be useful.

Typo: You should be Your in You other two ideas should be from domains not in this list, in order to broaden the brainstorm. Ensure the ideas are significantly different, not small variations on the same idea.

**Comment by fiannaca** [comment]
I though for the first homework, we were only going to have them brainstorm domains, not problems. the second exercise is designed to generate ideas of problems. 

It probably doesn't matter either way though.

**Comment by jayfo** [comment]
They do both in class, right?

I found in writing this out that just the domain felt "too short" to engage in.

**Comment by fiannaca** [comment]
Yes, they will be doing both in class.

**Comment by jayfo** [comment]
I think we're good.  :)
